#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: BookKeeper CI

on:
  pull_request:
    branches:
      - master
      - branch-*
  push:
    branches:
      - master
      - branch-*
  workflow_dispatch:

env:
  MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: ${{ matrix.step_name }}
    runs-on: ubuntu-latest
    timeout-minutes: ${{ matrix.timeout || 60 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - step_name: Bookie Tests
            module: bookkeeper-server
            flag: bookie
            test_args: "-Dtest='org.apache.bookkeeper.bookie.LedgerCacheTest'"

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Tune Runner VM
        uses: ./.github/actions/tune-runner-vm

      - name: Cache local Maven repository
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/apache/bookkeeper
            !~/.m2/repository/org/apache/distributedlog
          key: ${{ runner.os }}-bookkeeper-all-${{ hashFiles('**/pom.xml') }}


      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up Maven
        uses: apache/pulsar-test-infra/setup-maven@master
        with:
          maven-version: 3.8.7

      - name: Build
        run: |
          projects_list=
          if [[ ! -z "${{ matrix.module }}" ]]; then
            projects_list="-pl ${{ matrix.module }}"
          fi
          mvn -q -T 1C -B -nsu $projects_list install -am -DskipTests -Dcheckstyle.skip -Dspotbugs.skip -Drat.skip -Dmaven.javadoc.skip

      - name: Test - ${{ matrix.step_name }}
        run: |
          projects_list=
          if [[ ! -z "${{ matrix.module }}" ]]; then
            projects_list="-pl ${{ matrix.module }}"
          fi
          mvn -Pcode-coverage -B -nsu $projects_list verify ${{ matrix.test_args }}

      - name: Upload coverage to Codecov
        if: ${{ matrix.flag }} != 'shell'
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.flag }}

      - name: Aggregates all test reports to ./test-reports and ./surefire-reports directories
        if: ${{ always() }}
        uses: ./.github/actions/copy-test-reports

      - name: Publish Test Report
        uses: apache/pulsar-test-infra/action-junit-report@master
        if: ${{ always() }}
        with:
          report_paths: 'surefire-reports/TEST-*.xml'
          annotate_only: 'true'

      - name: Upload Surefire reports
        uses: actions/upload-artifact@v3
        if: failure()
        continue-on-error: true
        with:
          name: bookie-tests-reports
          path: surefire-reports
          retention-days: 7

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3

